/**
 * Copyright 2024-2026 Arm Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { openNewSolutionModal as defaultOpenNewSolutionModal } from '../new-solution-modal';
import { ConfigureVcpkgForSolution } from '../vcpkg/configure-vcpkg';
import { CommandsProvider } from '../vscode-api/commands-provider';
import { MessageProvider } from '../vscode-api/message-provider';
import { WorkspaceFoldersProvider } from '../vscode-api/workspace-folders-provider';
import { initialiseGit } from '../git-initialise/initialise-git';
import { CsolutionGlobalState, GlobalState } from '../vscode-api/global-state';
import { CreatedSolution } from './solution-creator';
import path from 'path';
import { CmsisSettingsJsonFile } from '../global/cmsis-settings-json-file';

type SolutionInitialiserOptions = {
    createdSolution: CreatedSolution;
    enableGit?: boolean; // defaults to false
    compiler?: string; // defaults to AC6
    showOpenDialog?: boolean; // defaults to false
}
export interface SolutionInitialiser {
    initialiseSolution(options: SolutionInitialiserOptions): Promise<void>
}

export class SolutionInitialiserImp implements SolutionInitialiser {
    constructor(
        private readonly commandsProvider: CommandsProvider,
        private readonly workspaceFoldersProvider: WorkspaceFoldersProvider,
        private readonly configureVcpkgForNewSolution: ConfigureVcpkgForSolution,
        private readonly messageProvider: MessageProvider,
        private readonly globalStateProvider: GlobalState<CsolutionGlobalState>,
        private readonly openNewSolutionModal = defaultOpenNewSolutionModal,
    ) {
    }

    public async initialiseSolution(options: SolutionInitialiserOptions) {
        const solutionDirUri = options.createdSolution.solutionDir;
        if (options.enableGit) {
            initialiseGit(solutionDirUri.fsPath, this.commandsProvider);
        }

        // Do not configure vcpkg for converted µVision projects: this would overwrite the vcpkg file generated by uv2csolution
        if (!options.createdSolution.vcpkgConfigured) {
            await this.configureVcpkgForNewSolution(solutionDirUri, [options.compiler ?? 'AC6']);
        }

        if (options.createdSolution.forceRteUpdate && options.createdSolution.solutionFile) {
            const cmsisJsonFile = path.join(solutionDirUri.fsPath, '.vscode', 'cmsis.json');
            const ccmsisJson = new CmsisSettingsJsonFile(cmsisJsonFile);
            await ccmsisJson.load();
            ccmsisJson.set('force-update-rte', true);
            await ccmsisJson.save();
        }

        await this.commandsProvider.executeCommandIfRegistered('keil-studio.initialise-project', solutionDirUri);

        const args = [
            options.createdSolution,
            {
                message: this.messageProvider,
                workspaceFolders: this.workspaceFoldersProvider,
                commands: this.commandsProvider,
            },
            this.globalStateProvider,
            !!options.showOpenDialog,
        ] as const;

        this.openNewSolutionModal(...args);
    }
}
